import {
    projImg1_1,
    projImg1_2,
    projImg1_3,
    projImg2_1,
    projImg2_2,
    projImg2_3,
    projImg3_1,
    projImg3_2,
    projImg3_3,
    projImg4_1,
    projImg4_2,
    projImg4_3,
    projImg5_1,
    projImg5_2,
    projImg5_3,
    projImg6_1,
    projImg6_2,
    projImg6_3,
    projImg7_1,
    projImg7_2,
    projImg7_3,
    projImg8_1,
    projImg8_2,
    projImg8_3,
    projImg9_1,
    projImg9_2,
    projImg9_3,
    projImg10_1,
    projImg10_2,
    projImg10_3,
    projImg11_1,
    projImg11_2,
    projImg11_3,
    projImg12_1,
    projImg12_2,
    projImg12_3,
    projImg13_1,
    projImg13_2,
    projImg13_3,
    projImg14_1,
    projImg14_2,
    projImg14_3,
} from "assets/images/projects"

export const projectsData = [
    {
        title: "Flight agency",
        description:
            "Start your journey with our flight agency website, where you can book flights, view travel deals, and get all the information you need to make your travel experience comfortable and hassle-free, including destination guides, luggage policies, and travel tips",
        images: [projImg5_1, projImg5_2, projImg5_3],
        tags: ["Web App"],
        technologies: ["React", "SCSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://sparkling-puffpuff-01ec61.netlify.app/",
        visit: "https://sparkling-puffpuff-01ec61.netlify.app/",
        id: 4,
    },
    {
        title: "Sushi restaurant",
        description:
            "Welcome to our sushi restaurant website, where you can explore our menu, make a reservation, and order your favorite sushi dishes online for pickup or delivery.",
        images: [projImg4_1, projImg4_2, projImg4_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/sushi-restaurant-website/",
        visit: "https://a-s-t-r-a.github.io/sushi-restaurant-website/",
        id: 3,
    },

    {
        title: "Delivery website",
        description:
            "Our idelivery website provides a convenient way to get your desired products delivered right to your doorstep, whether it be groceries, electronics, or household items, saving you time and effort from going out to the store.",
        images: [projImg2_1, projImg2_2, projImg2_3],
        tags: ["Web App"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-website-delivery/",
        visit: "https://a-s-t-r-a.github.io/responsive-website-delivery/",
        id: 1,
    },
    {
        title: "Halloween event",
        description:
            "Step into the spooky season with our Halloween event website, where you can find information on upcoming events and order items to get a taste of the Halloween fun you can expect.",
        images: [projImg3_1, projImg3_2, projImg3_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-halloween-website/",
        visit: "https://a-s-t-r-a.github.io/responsive-halloween-website/",
        id: 2,
    },

    {
        title: "Beats store",
        description:
            "Experience the ultimate in sound quality with our headphones store website, where you can browse a wide selection of headphones and audio accessories, read reviews, and make a purchase, all from the comfort of your own home.",
        images: [projImg1_1, projImg1_2, projImg1_3],
        tags: ["Web App"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-landing-page-headphones/",
        visit: "https://a-s-t-r-a.github.io/responsive-landing-page-headphones/",
        id: 0,
    },
    {
        title: "Restaurant website",
        description:
            "Savor the flavors of our restaurant website, where you can explore our diverse menu, book a table, and indulge in a culinary experience that combines traditional and modern dishes to satisfy all taste preferences.",
        images: [projImg6_1, projImg6_2, projImg6_3],
        tags: ["Web App"],
        technologies: ["React"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://stirring-phoenix-05f76a.netlify.app/",
        visit: "https://stirring-phoenix-05f76a.netlify.app/",
        id: 5,
    },
    {
        title: "Watches store",
        description:
            "Time is on your side with our watches website, where you can discover a wide range of watches for all occasions, from classic styles to the latest trends, and find the perfect timepiece to match your lifestyle and personality.",
        images: [projImg7_1, projImg7_2, projImg7_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-watches-website/",
        visit: "https://a-s-t-r-a.github.io/responsive-watches-website/",
        id: 6,
    },
    {
        title: "Christmas store",
        description:
            "Get in the holiday spirit with our Christmas store website, where you can browse a wide selection of festive decorations, gifts, and accessories, and bring the magic of the holiday season into your home and gift-giving.",
        images: [projImg8_1, projImg8_2, projImg8_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-christmas-website/",
        visit: "https://a-s-t-r-a.github.io/responsive-christmas-website/",
        id: 7,
    },
    {
        title: "Travel website",
        description:
            "This travel website offers a vast selection of destinations, accommodations, and activities, making it easy for travelers to plan and book their dream vacations.",
        images: [projImg9_1, projImg9_2, projImg9_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/responsive-travel-website/",
        visit: "https://a-s-t-r-a.github.io/responsive-travel-website/",
        id: 8,
    },
    {
        title: "Restaurant",
        description:
            "This restaurant website showcases their menu, location, and hours of operation, providing an easy and convenient way for customers to plan their visit and satisfy their cravings.",
        images: [projImg10_1, projImg10_2, projImg10_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://a-s-t-r-a.github.io/small-restaurant-js/",
        visit: "https://a-s-t-r-a.github.io/small-restaurant-js/",
        id: 9,
    },
    {
        title: "Coffee store",
        description:
            "This coffee store website offers a wide range of high-quality coffee beans, brewing equipment, and accessories to help customers create the perfect cup of coffee at home.",
        images: [projImg11_1, projImg11_2, projImg11_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://lambent-smakager-2aebe1.netlify.app/",
        visit: "https://lambent-smakager-2aebe1.netlify.app/",
        id: 10,
    },
    {
        title: "Blog website",
        description:
            "This blog website is a valuable resource for anyone looking to expand their knowledge on a variety of topics, featuring a diverse range of articles, opinions, and advice on everything from current events and lifestyle trends to business strategy and personal development.",
        images: [projImg12_1, projImg12_2],
        tags: ["Landing Page"],
        technologies: ["React"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://astra-blog.vercel.app/post/react-testing",
        visit: "https://astra-blog.vercel.app/post/react-testing",
        id: 11,
    },
    {
        title: "Real Estate",
        description:
            "This real estate website is a comprehensive platform for buying, selling, and renting properties, offering users access to a wide range of listings, professional agents, and helpful resources to navigate the complex world of real estate.",
        images: [projImg13_1, projImg13_2],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://real-estate-sable-six.vercel.app/",
        visit: "https://real-estate-sable-six.vercel.app/",
        id: 12,
    },
    {
        title: "E-commerce",
        description:
            "This e-commerce website offers a wide variety of top-rated headphones with detailed descriptions, customer reviews, and fast shipping.",
        images: [projImg14_1, projImg14_2, projImg14_3],
        tags: ["Landing Page"],
        technologies: ["HTML", "JavaScript", "CSS"],
        dates: {
            start: "14.05.2210",
            finish: "14.05.2210",
        },
        source: "https://ecommerce-art1us.vercel.app/",
        visit: "https://ecommerce-art1us.vercel.app/",
        id: 13,
    },
]
