export { technologiesData } from "./technologiesData/technologiesData"
export { timelineData } from "./timelineData/timelineData"
export { acomplishmentsData } from "./acomplishmentsData/acomplishmentsData"
export { dropdownData } from "./dropdownData/dropdownData"
export { aboutData } from "./aboutData"
