export { technologiesData } from "./technologiesData/technologiesData"
export { timelineData } from "./timelineData/timelineData"
export { projectsData } from "./projectsData/projectsData"
export { acomplishmentsData } from "./acomplishmentsData/acomplishmentsData"
export { dropdownData } from "./dropdownData/dropdownData"
